title: Leigh Freitag
description: US Navy | Supply Corps Officer | MS Operations Research candidate, NPS (proj Sep2027) | BS Computational Mathematics, GWU '15
logo: /images/picforgit.png
show_downloads: no
url: https://leighfreitag.github.io/
theme: jekyll-theme-minimal
